# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pool:
  vmImage: 'windows-latest'

variables:
  GitVersion.SemVer: ''
  GitVersion.NuGetVersion: ''

steps:
- task: UseGitVersion@5
  displayName: Version
  inputs:
    versionSpec: '5.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/Msq.Specification/Msq.Specification.csproj'
    arguments: '--configuration Release /p:Version=$(GitVersion.NuGetVersion)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'test/Msq.Specification.UnitTests/Msq.Specification.UnitTests.csproj'
    arguments: '--configuration Release --collect "Code Coverage"'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'nuget.org'

- task: NuGetCommand@2
  displayName: Publish
  inputs:
    command: push
    nuGetFeedType: external
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion    

